/*
 * bf
 * Copyright (C) 2022, bf contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "transpiler.h"

#include "common.h"
#include "tree.h"

#include <stddef.h>
#include <stdio.h>

#define TAB_SIZE 2

static void printTabs(size_t depth) {
    for (size_t i = 0; i < depth; i++)
        for (size_t j = 0; j < TAB_SIZE; j++)
            putchar(' ');
}

static void addLine(char *line, size_t depth) {
    printTabs(depth);
    puts(line);
}

static void transpileRecursive(struct BFTree *tree, size_t depth) {
    while (tree) {
        switch (tree->value) {
        case INC_POINTER_TOKEN:
            printTabs(depth);
            printf("incPtr(%hhu);\n", tree->count);
            break;
        case DEC_POINTER_TOKEN:
            printTabs(depth);
            printf("decPtr(%hhu);\n", tree->count);
            break;
        case INC_VALUE_TOKEN:
            printTabs(depth);
            printf("incValue(%hhu);\n", tree->count);
            break;
        case DEC_VALUE_TOKEN:
            printTabs(depth);
            printf("decValue(%hhu);\n", tree->count);
            break;
        case PUTCHAR_TOKEN:
            addLine("putcharInstruction();", depth);
            break;
        case GETCHAR_TOKEN:
            addLine("getcharInstruction();", depth);
            break;
        case START_LOOP_TOKEN:
            addLine("while (mem[ptr]) {", depth);
            transpileRecursive(tree->child, depth +1);
            addLine("}", depth);
            break;
        default:
            break;
        }
    
        tree = tree->pair;
    }
}

static void printLocalFunctions() {
    addLine("static void outOfBounds() {", 0);
    addLine("fprintf(stderr, \"error: memory pointer out of bounds\\n\");", 1);
    addLine("exit(1);", 1);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void incPtr(uint8_t n) {", 0);
    addLine("ptr += n;", 1);
    addLine("if (ptr >= MEM_SIZE)", 1);
    addLine("outOfBounds();", 2);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void decPtr(uint8_t n) {", 0);
    addLine("if (ptr < n)", 1);
    addLine("outOfBounds();", 2);
    addLine("ptr -= n;", 1);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void incValue(uint8_t n) {", 0);
    addLine("mem[ptr] += n;", 1);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void decValue(uint8_t n) {", 0);
    addLine("mem[ptr] -= n;", 1);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void getcharInstruction() {", 0);
    addLine("int input = getchar();", 1);
    addLine("if (input != EOF)", 1);
    addLine("mem[ptr] = (uint8_t)input;", 2);
    addLine("else", 1);
    addLine("mem[ptr] = 0;", 2);
    addLine("}", 0);
    addLine("", 0);

    addLine("static inline void putcharInstruction() {", 0);
    addLine("putchar((uint8_t)mem[ptr]);", 1);
    addLine("}", 0);
    addLine("", 0);
}

void BFTranspiler_run(struct BFTree *tree, size_t memorySize) {
    printf("/* Program generated by bf %s\n", VERSION);
    printf(" * %s\n", REPO_LINK);
    printf(" */\n\n");

    /* Headers and defines */
    addLine("#include <stddef.h>", 0);
    addLine("#include <stdint.h>", 0);
    addLine("#include <stdio.h>", 0);
    addLine("#include <stdlib.h>", 0);
    addLine("", 0);
    printf("#define MEM_SIZE %zu\n", memorySize);
    addLine("", 0);

    /* Global variables */
    addLine("size_t ptr = 0;", 0);
    addLine("uint8_t *mem = NULL;", 0);
    addLine("", 0);

    printLocalFunctions();

    /* Main function */
    addLine("int main(int argc, char *argv[]) {", 0);
    addLine("mem = calloc(MEM_SIZE, sizeof(uint8_t));", 1);
    addLine("", 0);

    transpileRecursive(tree, 1);

    addLine("", 0);
    addLine("return 0;", 1);
    addLine("}", 0);
}
